language: objective-c
osx_image: xcode8.2
script: xctool -workspace Demo/AGGeometryKitDemo.xcworkspace -scheme AGGeometryKitDemo -sdk iphonesimulator build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
